import Green from "./Green";
import Red from "./Red";
import Yellow from "./Yellow";

const component = [
  {
    component: <Yellow />,
    name: "yellow",
  },
  {
    component: <Green />,
    name: "green",
  },
  {
    component: <Red />,
    name: "red",
  },
  {
    component: <Yellow />,
    name: "yellow",
  },
  {
    component: <Green />,
    name: "green",
  },
  {
    component: <Red />,
    name: "red",
  },
  {
    component: <Yellow />,
    name: "yellow",
  },
  {
    component: <Green />,
    name: "green",
  },
  {
    component: <Red />,
    name: "red",
  },
  {
    component: <Yellow />,
    name: "yellow",
  },
  {
    component: <Green />,
    name: "green",
  },
  {
    component: <Red />,
    name: "red",
  },
];

export const cards = [
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
  ...component,
];
